### ISSUE TITLE
Account error

### ISSUE THREAD

**Issue by MrAlex8** [speckleworks/SpeckleServer#115]
#### Expected Behaviour
My colleague adds a speckle stream to the end of a dynamo script. We are in the same speckle project (as is the stream), with full writing rights. So I open the dynamo script and seamless transfer of data takes place.

#### Actual Behaviour
'Account error'!!!!

#### Affected Projects
Just the speckle sender

**Comment by didimitrie** [comment]
**Proposed solution**: client routes should check permissions on the client's stream rather than the client resource itself.
