### ISSUE TITLE
Docs for registering new user needs updating

### ISSUE THREAD

**Issue by bigdoods** [speckleworks/SpeckleServer#117]
Step 0: 
- [x ] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
How things should actually work!

First thing I do when I start a new server is register a user. I should copy code snippet from docs and it just works.

#### Actual Behaviour
What's actually going on!

The inputBody does not have a "password" key and thus the request fails with message "passwords are necessary evil..."

#### Affected Projects
Does this issue propagate to other dependencies or dependants? If so, list them here!

¯\_(ツ)_/¯

#### Reproduction Steps & System Config (win, osx, web, etc.)

Any client using docs as reference

#### Proposed Solution (if any)

Update the docs to indicate that a password key is required when creating a user

**Comment by logan12358** [comment]
Just checking, do you mean the docs here: <https://speckleworks.github.io/SpeckleSpecs/#userregister>? If so, this issue probably belongs on [speckleworks/SpeckleSpecs](https://github.com/speckleworks/SpeckleSpecs).

**Comment by bigdoods** [comment]
Issue moved [here](https://github.com/speckleworks/SpeckleSpecs/issues/32)
