### ISSUE TITLE
Allow duplicate clientIds & send a warning if it occurs

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleServer#120]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

### The problem 
Is actually in Rhino (and most probably in dynamo too): https://github.com/speckleworks/SpeckleRhino/issues/226

### The solution
While chatting with @logan12358, a way to solve this is to allow dupe client ids on the server instead of rejecting them outright and send a ws warning message to the culprits warning them that `this file is open in two places, you may get conflicts`.

**Comment by logan12358** [comment]
Is there a long-term fix where the Rhino plugin responds to the conflict warning by creating a new client? Allowing dupe clients seems like the sort of things that could easily cause problems later.

Perhaps an intermediate solution could involve some action on the Rhino nodes to "Generate new client" or something, to save rewiring, but still alert the user that a new client is being created.

**Comment by didimitrie** [comment]
Good shout. Short term, to alleviate the "red nodes" stress, we'll just make the clients respond with a warning of sorts in the gh ui (the rhino ui needs a re-write and isn't afaik so much in use as the gh one) & patch this on the server.

Long term fix, if this is detected, and it's a sender, what you suggest is correct (generate new client & another stream as a child of the original). But the usage that i see is many people "collaborating" on one file, so this doesn't make sense in that context.

**Comment by logan12358** [comment]
Oh right, so the idea is that one GH script should correspond to one Speckle client? Even if the file gets passed around or opened simultaneously?

**Comment by didimitrie** [comment]
Yep! one client = one receiver **or** one sender. If the file gets passed around, theoretically that client should update himself with his new location/file name/etc (when it's opened again). 

The web viewer registers also _n_ clients, one for each stream that's opened in it (i think they get deletd when they get disposed) - again, if i remember correctly.

**Comment by logan12358** [comment]
To fix the "collaboration" case, would it work to have:
- Sender nodes create a new Client whenever they're opened from a new location or on a new computer, with their DocumentLocation set to reflect that (and maybe prompt the user for a description of their branch). The might also need to create a new Client if they're opened twice on the same machine, but that might be a case where a red node is acceptable. The idea would be that you maintain a strict "one sender to one stream" relationship.
- Receiver nodes have slightly more facility for exploring the parent/child graph, both temporarily (previewing a different stream) and permanently (persisted to the saved GH/Dynamo file).
