### ISSUE TITLE
Object Put and Object Put Properties do not modify object hash

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleServer#121]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

#### Expected Behaviour
Changing the property of an object should, according to the speckle mantra, create a new object with  the modified property and its corresponding hash. 

#### Actual Behaviour
That's  not happening. The controllers in question do not do that [1](https://github.com/speckleworks/SpeckleServer/blob/master/app/api/objects/ObjectPutProperties.js) [2](https://github.com/speckleworks/SpeckleServer/blob/master/app/api/objects/ObjectPut.js). 

#### Affected Projects
Server only. 

#### Proposed Solution (if any)
1) Remove the object put properties controller (as it's redundant! - one should just use the object put route with a body prop called `properties` if that is what one wants to do). 
2) Implement the speckle mantra - duplicate the object, set the corresponding props with the new ones, update the hash, save it and return the new hash & objectId.

**Comment by logan12358** [comment]
I have a local branch where I implement "ObjectDerive" which is pretty much this, as a POST endpoint alongside "ObjectPut". I should be able to turn it into what you want here pretty easily.

Since it's creating a new object, can new method be a POST one? Or does that change the API too much?

Also, affected projects should include the Specs! And any client that currently relies on ObjectPut.

**Comment by didimitrie** [comment]
Sounds good. And then can we make it work for array inputs - as in, bulk by default? (this might throw a spanner in the works). I agree we should keep ObjectPut as a predictable "classic" endpoint, and go for `derive`. 

I might need this today so I'll poke in your fork. 

I see you did 
```
r.post( '/objects/:objectId', mandatoryAuthorisation, require( './objects/ObjectDerive' ) )
```

I'll propose something frowned upon in the api world, as a temp measure, and add a verb in the url
```
r.post( '/objects/derive', mandatoryAuthorisation, require( './objects/ObjectDerive' ) )
```
and req.body should be formatted with SpeckleObjects with the props that need modification.

**Comment by didimitrie** [comment]
closing for now, as it's been implemented above
