### ISSUE TITLE
Enhancement - Tag docker images with semantic version

### ISSUE THREAD

**Issue by AntoineDao** [speckleworks/SpeckleServer#131]
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
Dockerhub images should have `latest` tag as well as semver version tags.

#### Actual Behaviour
The Docker images on Dockerhub are tagged:
- latest
- dev
- nightly

For the most part they have not been updated in over a year (except `latest`).

#### Affected Projects
Testing and development of Python client and backwards compatibility.

#### Reproduction Steps & System Config (win, osx, web, etc.)
N/A

#### Proposed Solution (if any)
Use [semantic-release](https://github.com/semantic-release/semantic-release) to automate semver number increase, releases on github and deployment to dockerhub.I've done this on other projects so happy to discuss/help implement.

**Comment by AntoineDao** [comment]
Might also be nice to fix the mongodb and redis versions in `docker-compose.yml` for sake of explicitly marking dependencies.

**Comment by didimitrie** [comment]
Hello @AntoineDao , i haven't looked at the docker image in quite a while, that's true. This sounds good! As long as no extra complications on the build side of things, happy to automate the semver number increase! 

Let me know if you will need access to the dockerhub speckle org etc. as i'm not sure what permissions you will need to enact this change.

**Comment by AntoineDao** [comment]
Well... semantic-release will require some rigour on the developer side as it requires a pretty strict commit message style ([angular conventional changelog](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines)). If you can get buy in from devs then setting up is relatively straightforward:
1. Setup a travis file 
2. Add some tests (come on, you know you should!)
3. Write deploy to docker as part of semantic release in `.travis.yml`

Only input required by you will be to add dockerhub user and password as secret variables in travis UI (I don't need to be involved in that process at all, safe that way 😄 )

**Comment by AntoineDao** [comment]
PS: writing conventional log messages is a piece of p**s if you use [`commitizen`](https://github.com/commitizen/cz-cli). I got the ladybug tools team to just about adopt it and it's made this whole CI/CD thing a breeze. Here's your one line install to start playing with it:
> npm install -g commitizen cz-conventional-changelog && echo '{ "path": "cz-conventional-changelog" }' > ~/.czrc

Note: you need to have nodejs installed locally

**Comment by didimitrie** [comment]
@AntoineDao , we can reopen this if you want to have the honour of closing it ;)
