### ISSUE TITLE
User search producing inconsistent results

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleServer#154]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

Reports of inconsistent results for search users start to abound. I suspect this is an old bug that we're just discovering.

**Comment by tomhebunn** [comment]
Additional information:

User search appears not to be picking up full contact list when trying to add to project. A search of 'Arup' produces 10 results when many more are expected.
