### ISSUE TITLE
Child streams are not created 

### ISSUE THREAD

**Issue by mswaidan** [speckleworks/SpeckleServer#37]
e.g. https://s003.speckle.works/api/streams/HkpvHF8pZ

**Comment by didimitrie** [comment]
This might be a bug in the gh plugin, that actually does not clone the streams properly. I'll have to check in both repos, though thinking about it i suspect the server is safe...

**Comment by PaulPoinet** [comment]
Just for info, I successfully created child streams using the API

**Comment by didimitrie** [comment]
yeps, the problem is in the Defintion Controller GH component here: https://github.com/speckleworks/SpeckleGrasshopper/blob/dev/ExtendedComponents/GhExtendedClients.cs#L101
