### ISSUE TITLE
>16mb docs kill mongo + app

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleServer#39]
When a user tries to insert a huge doc, ie a mesh with >100k vertices or some sort, mongo goes crazy, topology gets destroyed (sounds like a wizard spell) and a full server restart is needed (mongod + app). 

How to protect from this/work around this? 
- clients should not send this kind of requests in the first place
- different storage engine for mongo/big objects (wired tiger vs. gridfs)
- ...

**Comment by bigdoods** [comment]
I would suggest patch it for now so the server will reject objects over
said limit.

Have you tested a different storage engine or considered a different db
technology?

What about the idea of splitting large objects and storing relationships in
a graph?

**Comment by didimitrie** [comment]
@bigdoods all good suggestions! 

- **Short term**: server accepts payloads only under 10mb going forward. 
- **Medium term**: clients should be able to handle, stop and communicate size of payloads.
- **Long term**: switch object storage to a different system.

Splitting large objects, etc: speckle does nested objects via the objects properties. Had some chats with @teocomi some weeks ago and a different storage engine for this would be beneficial (neo4j anyone?). Streams and everything else can essentially go in a normal relational db, and objects and their relationships would go into a graph db.

An argument against going to something like s3 buckets for objects will be a less evident way of querying, though this can be mitigated with good metadata storage.

**Comment by didimitrie** [comment]
Short term plan implemented and deployed on s003.speckle.works - see #40 
Not closing this and i'm sure it's going to be here a while. 

Medium term should actually be an issue in both speckle core as well as the gh and rh plugins

**Comment by didimitrie** [comment]
Closing this as it's no longer a server side issue. Future, better data storage mechanisms - for the future
