### ISSUE TITLE
Create "Deploy to Heroku" button 🛳

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleServer#51]

**Comment by radumg** [comment]
yes please :)

**Comment by pearswj** [comment]
Alas, the Heroku Button [doesn't support submodules](https://devcenter.heroku.com/articles/heroku-button#requirements)... :\

**Comment by didimitrie** [comment]
😢 I am actually wondering if the viewer submodule is a necessity. It could be part of the dockerfile? Something on the lines of 
```
# etc. 
RUN git clone https://github.com/speckleworks/SpeckleViewer in folder /static/view
# then also
RUN git clone https://speckleadmin in folder /static/admin
#...

```

Would this be easier to translate to heroku's `app.json`? Or a better general strategy overall?

**Comment by pearswj** [comment]
I don't think that will help with `app.json`. Still, deploying via manually to Heroku via git is not a difficult task. I'll document that as a starting point.

**Comment by didimitrie** [comment]
okays, when there's time. this issue started more as quip on are you read to 🚢
