### ISSUE TITLE
Get rid of viewer submodule and add it as a step in the docker image

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleServer#57]
Open question: should the viewer be a submodule (as it is now), or essentially a step in the `Dockerfile` image (`RUN git clone etc`)? Bearing in mind this would/should expand to other front-end apps, etc.

any help/info welcome. bear in mind, main point is to get the install of a speckle server as simple as possible...

**Comment by pearswj** [comment]
I guess when you start talking about custom front end apps, submodules don’t make for the most user friendly experience

**Comment by pearswj** [comment]
`RUN git clone -b 'v1.1.2' --single-branch --depth 1 https://github.com/SpeckleWorks/SpeckleAdmin.git static/admin`

**Comment by didimitrie** [comment]
that's  a release tag i spy there?

**Comment by pearswj** [comment]
Yeah. If you go the Dockerfile route then this seems like a nifty one-liner to check out a specific version of a “front end” repo.

**Comment by didimitrie** [comment]
smooth. then we'll go this route, it looks cleaner (until we mismatch versioning). `RUN git clone -b 'v1.1.2' --single-branch --depth 1 https://github.com/SpeckleWorks/SpeckleViewer.git static/view`, etc, etc. 

Super thanks for unblocking this!

**Comment by didimitrie** [comment]
log:  speckleadmin seems to work nicely as an npm module. I think when we have speckleworks/SpeckleViewer#23 ready as an  npm package we can go down that road...

**Comment by didimitrie** [comment]
i've npm'ed the viewer too: https://www.npmjs.com/package/@speckle/speckle-viewer and added it as package.json dependency with, for now, `@latest` tag. 

So now, when you do an `npm install` of the server, you get your viewer as well as the admin ui 🙌
