### ISSUE TITLE
Update docker-compose

### ISSUE THREAD

**Issue by bigdoods** [speckleworks/SpeckleServer#70]
Docker-compose should use a specific tag with image that it pulls. I updated the compose from dev -> latest as it was pulling dev image which was built 2 months ago and did not contain latest API updates. speckle/speckleserver:v1 would be a good suggested tag to use here. Todo: Build and push to dockerhub.

**Comment by didimitrie** [comment]
There's an automated build going on for master and dev branches.

![image](https://user-images.githubusercontent.com/7696515/38298851-733962d4-37f0-11e8-9ec4-ea7966ab3b24.png)

I forgot to merge the 1.0.0 changes into dev, just did so. Whenever we push into  either of those branches, we should get an automated build going.

**Comment by bigdoods** [comment]
Does this mean that master branch is the equivalent to production? 

If so, docker-compose will have a difference of not using port forwarding on the db's for master but may be useful for dev for using local mongo client etc to query..
