### ISSUE TITLE
Get rid of nasty logging on security middleware

### ISSUE THREAD

**Issue by didimitrie** [speckleworks/SpeckleServer#73]
Radu [10:04 PM]
hmm, is this expected behaviour @dimitrie? when registering a new user, the user password is dumped in cleartext in the logs
Radu [10:04 PM]
uploaded this image: image.png

**Comment by radumg** [comment]
![image](https://user-images.githubusercontent.com/11439624/38473522-2ef991f6-3b89-11e8-9d74-ccbc0ac393c9.png)
