### ISSUE TITLE
User emails can be exfiltrated

### ISSUE THREAD

**Issue by logan12358** [speckleworks/SpeckleServer#92]
Step 0:
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!

#### Expected Behaviour
You should not be able to trawl for emails.

#### Actual Behaviour
You can get everyone's emails.

#### Affected Projects
Affects [speckleworks/SpeckleSpecs](https://github.com/speckleworks/SpeckleSpecs) and [speckleworks/SpeckleAdmin](https://github.com/speckleworks/SpeckleAdmin), at least.

#### Reproduction Steps
To get emails quickly:
1. [Search](https://speckleworks.github.io/SpeckleSpecs/#usersearch) for users by email (this doesn't return email, but does return id)
2. [Get](https://speckleworks.github.io/SpeckleSpecs/#usergetprofilebyid) user by the id returned above

Alternatively, you can abuse regex/substring matching:
1. Repeatedly [search](https://speckleworks.github.io/SpeckleSpecs/#usersearch) for users with queries like "`john.smi[a-m].*`", narrowing down options until you find full email addresses

#### Proposed Solution

- [x] Don't return emails from the [`UserGetProfileById`](https://github.com/speckleworks/SpeckleServer/blob/master/app/api/v1/accounts/UserProfile.js) endpoint.
- [x] Only search by substrings of name and company?
- [x] Consider other methods of permissions (e.g. `EXPOSE_EMAILS` parameter in `.env`, per-user publicity flag?)
- [ ] Check how these issues manifest in the v0 api, and resolve them if applicable.
- [ ] Update specs
- [ ] Update admin app

**Comment by didimitrie** [comment]
I'll chime in with some extra context from @logan12358 and me chat on slack re this:

The confusing labels on this one come from an earlier unfinished discussion surrounding the context of this issue: how/for what is a speckle server deployed? 

1) per company/per project: email visibility is actually cool, as you should know your employees, collaborators, etc.
2) as a service for all: evidently not cool. 

Therefore my vote would go for the env var...

**Comment by logan12358** [comment]
I think that an env var is a good solution for now. In the future I think it might be useful to explore more granular permissions, along with more extensible user properties. But that's probably outside the scope of this issue, and also something you might already have plans for..

**Comment by didimitrie** [comment]
you've fixed this, no @logan12358? I'll close

**Comment by logan12358** [comment]
There are still those last couple of checkboxes, but I can just work through those. Just made speckleworks/SpeckleSpecs#28 for the specs.

**Comment by logan12358** [comment]
Just looking at the v0 API endpoints, they seem very similar to the v1 ones. Do any other parts of Speckle depend on them? Should I apply the same changes (with environment variable) to the v0 endpoint?

**Comment by didimitrie** [comment]
Re v0, I think now nobody is using it anymore (hopefully all plugins got updated), so it can be even removed all together now!
