### ISSUE TITLE
Can't deploy to Heroku

### ISSUE THREAD

**Issue by mitevpi** [speckleworks/SpeckleServer#98]
Playing around with setting up a Speckle server and am having some issues getting it up and running. I made my droplet, and ran these commands from the readme:
![image](https://user-images.githubusercontent.com/25568566/47365308-462d6f80-d6a9-11e8-940d-04de1a0d04be.png)

Afterwards, in the same terminal of the droplet, I used the commands below:
![image](https://user-images.githubusercontent.com/25568566/47365344-5e9d8a00-d6a9-11e8-95ef-c99e461afb55.png)

However the messsage I keep getting is this: 
![image](https://user-images.githubusercontent.com/25568566/47365376-6b21e280-d6a9-11e8-9946-a673b3185d10.png)

Any idea what I'm doing wrong here? Also - after the "docker-compose up" command, should the process be left running? I ended it with Control+C so that I could execute the heroku commands in the droplet.

**Comment by didimitrie** [comment]
Droplets are on digital Ocean, heroku is another provider! If on heroku, I will have to defer to will as he's the one that set it up!

**Comment by mitevpi** [comment]
Thanks @didimitrie - I'm a complete beginner at this so please excuse my ignorance. If I wanted to just do the digital ocean route - is this tutorial the most recent guide? https://speckle.works/doc/deployaserver/

**Comment by didimitrie** [comment]
@mitevpi, no worries.  this is my bad: the whole `/doc/*` should be removed, as it's out of date. Up to date instructions are in the readme: https://github.com/speckleworks/SpeckleServer/blob/master/readme.md#5-minute-docker-install-%EF%B8%8F-with-digital-ocean

**Comment by mitevpi** [comment]
@didimitrie thanks - so after the `docker-compose up` command, how do I get my speckle server API url for the Rhino plugin:
![image](https://user-images.githubusercontent.com/25568566/47370890-aece1980-d6b4-11e8-89db-e697a62bbe76.png)

**Comment by mitevpi** [comment]
Thanks - FYI whatever I get working, I'm happy to contribute to the Documentation. 

**Digital Ocean**
So currently have my droplet running `docker-compose up` and these are the specifications: 
![image](https://user-images.githubusercontent.com/25568566/47372572-09b54000-d6b8-11e8-836e-7fc4a35b824d.png)

But when I follow your template and go to: https://68.183.22.231:3000/api/v1, it doesn't seem to show anything. I added the firewall protocol from the readme as well.

**Heroku**
I can push and build successfully, but the app can't be accessed. The logs show the following:
![image](https://user-images.githubusercontent.com/25568566/47372921-c5766f80-d6b8-11e8-85f1-781aa653cfb0.png)

**Comment by didimitrie** [comment]
with docker, run `docker-compose up -d` to "detach", and run things in the background.

**Comment by mitevpi** [comment]
@didimitrie interesting. It works with http but not with https when I follow your formula: `https://YOUR_DROPLET_IP:3000/api/v1`

**Comment by didimitrie** [comment]
i'll close for now, but if problems persist, hit us up!
