### ISSUE TITLE
Q: Is it possible to connect to a locally hosted server?

### ISSUE THREAD

**Issue by dimven** [speckleworks/SpeckleServer#99]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
I'm trying to set up a a locally hosted server and evaluate the feasibility on hosting it on an internal network, disconnected from the internet. From what I can tell, the server seems to be running fine and I can contact it from the browser. However any attempt to contact it from other apps (eg. Dynamo, REST clients) seems to fail.

![image](https://user-images.githubusercontent.com/7148394/48314548-cb82b080-e5d3-11e8-8242-be7d8185a480.png)

![image](https://user-images.githubusercontent.com/7148394/48314561-0dabf200-e5d4-11e8-8be8-ab915235112c.png)

Dynamo:
![image](https://user-images.githubusercontent.com/7148394/48314576-3633ec00-e5d4-11e8-96c3-e0150026da1b.png)
Insomnia:
![image](https://user-images.githubusercontent.com/7148394/48314606-75fad380-e5d4-11e8-9a95-10ad908dc9df.png)

I've tried changing the port of the speckle server to port 80 and turning off the firewall, but that doesn't seem to make a difference. Do I need to explicitly add exceptions to speckle in the firewall? If so, any tips on how that should look in win 10?

![image](https://user-images.githubusercontent.com/7148394/48314702-c4f53880-e5d5-11e8-8f55-157a7ed2dca6.png)

Thank you for all your efforts developing this great platform and for any help you might offer with the current issue.

**Comment by dimven** [comment]
attaching the login information as a body seems to work as expected from the REST client:

![image](https://user-images.githubusercontent.com/7148394/48314851-4948bb00-e5d8-11e8-8197-2b99d9aa42ed.png)

**Comment by mswaidan** [comment]
Hi @dimven 

You need to put the "/api/v1" at the end of the server URL in Dynamo. That should probably be more explicit. See https://discourse.speckle.works/t/deploying-a-speckle-server/57/15

**Comment by dimven** [comment]
Aha, that's an easy solution! :)
Thanks a lot
